### ISSUE TITLE
Unable to get dotnetapp-prod working

### ISSUE THREAD

**Issue by aaronjones** [dotnet/dotnet-docker-samples#31]
In the directions here: https://github.com/dotnet/dotnet-docker-samples/blob/master/dotnetapp-prod/README.md

I am unable to make the 1st command (dotnet restore) execute successfully, let alone any of the subseqent commands... I had assumed with your last update to the repo that something was changing in .NET Core 1.1 to leverage the csproj file rather than the project.json declaration (not being up on all the latest Core advances doesn't especially help me here).  At the end of the day I wanted to get a basic .NET Core Docker server up and running.  I will poke around with the other ones, though it appears reasonably obvious that this one does not work as advertised :-)

Likely unrelated but something else I noticed is that when I go to: https://www.microsoft.com/net/download/core#/current
and download the x64 version of .NET Core 1.1 it comes down as "dotnet-dev-win-x64.1.0.0-preview2-1-003177".  Perhaps I am incorrect in assuming that I should be seeing ...x64.1.1... ?  After ensuring that is installed and executing dotnet --version it comes back (as one would expect) 1.0.0-preview2-1-003177, though everything being numbered friendly to the rest of the Internet's commentary sure would be nice.

**Comment by aaronjones** [comment]
I installed Visual Studio 2017 community edition (I already had 2015 installed before), and a restart was forced post installation of 2017.  Now the demo seems to work.
Either
1) a restart was required after I installed dotnet-dev-win-x64.1.0.0-preview2-1-003177 previously, and if I had, then the projects would have run.
or
2) something in that ginormous VS2017 install is what was required in order to make it work.

I will attempt commandeering my sons laptop in the coming days to see if it was #1, or if perhaps some updates in the README will be required for others to get this working from the commandline.  I do notice when I now call "dotnet --version" that is spits back "1.0.0-rc4-004771" due to VS2017 being installed.

**Comment by MichaelSimons** [comment]
@kendrahavens - it looks like the instructions should provide more clarity on exactly which version of .NET Core is required.  Currently the instructions reference [.NET Core](https://www.microsoft.com/net/core#windowsvs2015) which can get you into installing preview2 or preview2-1 bits.  These samples require an msbuild based SDK therefore the instructions should be more explicit.  Can you add clarification?

**Comment by kendrahavens** [comment]
@aaronjones Thank you for pointing this out! We should definitely provide clarity that the samples require a MSBuild-based version of .NET Core since our most recent update. I'll update the READMEs. 

We have an interesting situation where the 1.1 .NET releases that are **officially** supported are still project.json based. That's why you don't see them on [https://www.microsoft.com/net/core](https://www.microsoft.com/net/core) **yet**. The 1.1 .NET Core download that is msbuild-based is our "RC" release that accompanies VS2017 releases. It was the VS2017 RC4 install that included the .NET Core download: 1.1 with SDK RC4 build 004771. This 4771 build is MSBuild-based. Therefore, it was definitely # 2 that fixed your set up. To see a list of our release history you can checkout our [release notes](https://github.com/dotnet/core/tree/master/release-notes).

This versioning scheme is going to be simplified when 2.0 comes out, but your note on the x64 version of .NET Core 1.1 coming down as "dotnet-dev-win-x64.1.0.0-preview2-1-003177" being [confusing is definitely a recorded issue](https://github.com/dotnet/core/issues/428) with .NET Core versioning. The 1.1 refers to the version of the .NET libraries that are included. The "1.0.0-preview2-1" is the version of the .NET Core CLI. We are planning on the 2.0 release solving a lot of the confusion by uniting the numbering on the different components of .NET Core.

**Comment by MichaelSimons** [comment]
Closing per @kendrahavens fix.

**Comment by gforceg** [comment]
I'm running Fedora 24. According to the " '1.0.1' was not found" message, I have the following versions intalled: 1.1.1, 1.1.0, and 1.0.0.
Is there a page with all of the prior fedora builds listed so that I can download the one my project requires?
Thanks,

**Comment by kendrahavens** [comment]
@gforceg There was a .NET Core release today that should fix your problem. Try installing the latest release [.NET Core 1.1.1](https://www.microsoft.com/net/core#linuxfedora) locally on your Fedora 24 machine. Let us know if you have any issues.

**Comment by gforceg** [comment]
Works like a charm!
Thank you @kendrahavens
