### ISSUE TITLE
`dotnet build` on CentOS sets wrong runtimeOptions.framework.version

### ISSUE THREAD

**Issue by chgeuer** [dotnet/dotnet-docker-samples#57]
I tried a multi-stage docker build of a simple .NET Core app. Repro here:

https://gist.github.com/chgeuer/84c6430f720ad207079621113475756e

1. On CentOS 7.3.1611, I use the `dotnet-dev-centos-x64.1.0.4.tar.gz` binary from Microsoft to `dotnet publish` the app. 
2. On the runtime system, I use `dotnet-centos-x64.1.0.5.tar.gz` to execute the binary. 
3. For the release to actually launch, I must modify the contents of the `app.runtimeconfig.json` file's `runtimeOptions.framework.version` property to  `1.0.5`. For some reason, the SDK 1.0.4 sets the value to `1.1.2` when calling `dotnet build`. So after the build step, I'm forced to [modify the value to 1.0.5}(https://gist.github.com/chgeuer/84c6430f720ad207079621113475756e#file-dotnetcoreoncentos-dockerfile-L37):

```
cat ${APPNAME}.runtimeconfig.json | jq ".runtimeOptions.framework.version |= \"${DESIREDVERSION}\"" > ${APPNAME}.runtimeconfig.json.updates
```

**Comment by MichaelSimons** [comment]
Assigning to @kendrahavens to investigate.

**Comment by kendrahavens** [comment]
Hi @chgeuer. The 1.0.4 sdk shipped with two versions of the runtime. It has both 1.0.5 and 1.1.2. runtimes.  When you ran the `dotnet new console` command it automatically chose the 1.1.2 runtime because the default target framework in your csproj is netcoreapp1.1. Change the `dotnet new console ` line to have a `-f netcoreapp1.0` flag to initialize an app that uses the 1.0 libraries and 1.0.5 runtime. That should eliminate the need to change your json files.

**Comment by chgeuer** [comment]
Great, thanks.
