### ISSUE TITLE
When should tests be run?

### ISSUE THREAD

**Issue by bezysoftware** [dotnet/dotnet-docker-samples#75]
I'm looking at this Dockerfile https://github.com/dotnet/dotnet-docker-samples/blob/master/aspnetapp/Dockerfile
and I'm wondering - when and how should tests be run, when building the image on a CI server?

Lets imagine we have following (typical) structure:
```
demo.sln
demo/*
demo.test/*
```

I would like to build the image as in the samples, but at which point should the tests be run? Should that be part of the image creating process (probably not, because that would slow down local debugging, as tests would be run each time)? Should the test project has it's own separate image build and then somehow connect the two? How do I avoid building the sources twice (once the demo project, then the test project, which has dependency on the demo project)?

**Comment by kendrahavens** [comment]
There are a lot of different ways you can run tests in a container and the best way for you will probably be very specific to your workflow.

Some main questions will help decide how this should be done:

1. Do you want your tests to run as part of the publishing step?
   - The advantage would be you can run the tests as one stage of a multi-stage build Dockerfile.
   - The disadvantage would be you'd have to run tests every time you wanted published output.
   - Fortunately you can actually avoid the hassle you mention above where adding a test step would slow down local debugging because you can pass build arguments to only build up to a certain step in a Dockerfile. (For example, to stop after the build step in the Dockerfile you would pass `--target buildstep` where `buildstep` is whatever you named that step in the Dockerfile.)
2. How do you want to capture test output?
   - It may be harder to capture console output if you run tests as part of `docker build`.
   - If the pass/fail output that prints to the console is all you need then running tests as one step in a multi-stage build would not be a problem. For this you'd want a Dockerfile with a test step inserted similar to below where the WORKDIR in the `test` step is your test project.
```Dockerfile
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore & dotnet build

#This is the test step
FROM build-env AS test
WORKDIR /app/aspnetapp.Test
RUN dotnet test

#This is the publish step
FROM build-env AS publish
WORKDIR /app
# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image, This is the production step
FROM microsoft/aspnetcore:2.0 AS production
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```
3. Are you looking to Docker to meaningfully redesign your CI/CD flow?
   - Right now, if you want to run tests in a container, but ***not*** as a step in a multi-stage build Dockerfile you will need some scripting to relate the build, test, and publish steps as part of your CI/CD pipeline.
   - The disadvantage is the extra script writing required to build your own pipeline where the test step is outside of the build and publish steps.
   - The advantage is having more control over when you spend server resources to accomplish building, testing, and publishing.
4. Are you actively developing tests?
   - If you are actually focused on writing tests and the app they are running against is not in active development then the flow could also be different. In this case you would not wish to re-build your entire sln, but only build and run the test project against your finished `demo` app. In this case, you may want a separate test container to mount the folder it needs to reference and only build the test project.

We definitely haven't determined one prescribed way of running tests in containers because it can be very scenario dependent, but you bring to light that we should document the options in a few test-focused sample projects. (Thank you!) What I mention above also doesn't begin to describe how to integrate this with pre-existing CI/CD flows one might have in VSTS or Jenkins.

I'd be interested to hear what other factors affect the "test in containers" workflow that I haven't listed above.

@bezysoftware If you'd like to go into more specifics or want to chat offline let me know! My email is kehavens ****** @****microsoft.com. (Without the asterisks or spaces. I added those to avoid the bots.)

**Comment by kendrahavens** [comment]
Closing if there are no further comments. Feel free to comment if you'd like to continue discussion. We are definitely actively working on creating a "golden path" scenario that we would recommend to customers, but it is still in the works as other parts of the container ecosystem develop.
