### ISSUE TITLE
Should the arm example not be compiled with the -r linux-arm option?

### ISSUE THREAD

**Issue by paulvanbladel** [dotnet/dotnet-docker-samples#82]
I tried following docker file on a raspberry pi.
Well, obviously I built the docker image on a x86 machine, but pull and run the created image on a pi.

https://github.com/dotnet/dotnet-docker-samples/blob/master/dotnetapp-prod/Dockerfile.arm32#L2

I only got it working when adding -r linux-arm.
RUN dotnet publish -c Release -o out
===> RUN dotnet publish -c Release -o out -r linux-arm

Warm regards
paul.

**Comment by MichaelSimons** [comment]
Greetings Paul

Are you building the dotnetapp-prod sample verbatim?  Can you explain what your build Docker Host looks like (e.g. what is the output of `docker info`)?

If you specify -r linux-arm you are producing a self-contained app which includes the Shared Framework.  If used with the `runtime` images you would be carrying two copies of the Shared Framework.  Self-contained apps are intended to be used with the `runtime-deps` image.  See the [self-contained sample](https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-selfcontained).

**Comment by paulvanbladel** [comment]
Hi Michael,
Thanks a lot for the prompt feedback.
I'm using the 2 stage approach.  Stage 1 is the build stage (with aspnetcore-build:2), Stage 2 is the runtime stage.
My workflow is first doing a docker build on a x86 machine, then push the image to docker hub. 
Then, on a raspberry pi I pull the image from docker hub and run it.
That scenario works perfectly with following dockerFile (see lower).
So, what I understand now is that I should better use the runtime-deps image.

Is it expected behavior that with my dockerfile (so using runtime-stretch-arm32v7) everything works as well (at least when compiling with -r linux-arm)?
Is the runtime-deps image,  currently the only  image for the stage 2, that I could use and that would work on a raspberry pi? 
Thank a lot.
paul.
```
# Build stage
FROM microsoft/aspnetcore-build:2 AS buildenv
WORKDIR /temp
ENV projectname api
COPY ${projectname}/${projectname}.csproj ./${projectname}/
RUN dotnet restore ${projectname}/${projectname}.csproj
COPY ./${projectname} ./${projectname}
RUN dotnet publish ${projectname}/${projectname}.csproj -o /publish -r linux-arm -c Release  
# RUN dotnet publish ${projectname}/${projectname}.csproj -o /publish -c Release  --> This will not work when using the docker image on a raspberry pi

# Runtime stage
FROM microsoft/dotnet:2.0.0-runtime-stretch-arm32v7
ENV dllname api.dll
COPY --from=buildenv /publish ./publish
WORKDIR /publish
ENV ASPNETCORE_URLS http://0.0.0.0:80
EXPOSE  80
ENTRYPOINT dotnet "${dllname}"

**Comment by MichaelSimons** [comment]
Hi Paul,

I believe you are encountering the issue described in https://github.com/dotnet/dotnet-docker/issues/279.  The TLDR is the runtime image you are using doesn't include the ASP.NET Core Runtime Store which is needed to run a [Framework-Dependent Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/#framework-dependent-deployments-fdd) ASP.NET core app.  ASP.NET Core does not have ARM Docker images yet (note [arm support is in preview](https://github.com/dotnet/announcements/issues/29)).  It works when you specify `-r linux-arm` because you are triggering a [Self-Contained Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd) which will include all of the necessary components needed to run the app in a standalone fashion.  

Another workaround aside from using a self-contained deployment with the `runtime-deps` image would be to simply add the following to your project.  This will then allow you to use the `runtime` image.
```
<PropertyGroup>
   <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup>
```

**Comment by MichaelSimons** [comment]
@glennc, @natemcmaster - Are ARM runtime images on the ASP.NET Core radar?

**Comment by natemcmaster** [comment]
@MichaelSimons we're aware of it, but no work has been done yet. We're tracking the request for linux-arm support here: https://github.com/aspnet/Universe/issues/554.

**Comment by paulvanbladel** [comment]
@MichaelSimons 
That's definitely a good solution for what's I'm doing right now with the Pi, dotnet core and docker.
For me this issue/question can be closed. (please advice)
A big thank you for all the amazing things you are doing with .net core and docker. 
The combination of docker and .net core, the devops opportunities make, at least for me, that .net is again the number one framework allowing very reliable apps in an amazing ecosystem of possibilities with the smallest footprint possible.  Great work.

**Comment by MichaelSimons** [comment]
Thank Paul, glad to hear you are liking docker and .NET Core!
