### ISSUE TITLE
Add remote debugging support

### ISSUE THREAD

**Issue by jamestharpe** [dotnet/dotnet-docker-samples#83]
It would be great if we could debug an the application running in the development docker container.

**Comment by kendrahavens** [comment]
@jamestharpe You can absolutely debug through a development Docker container with [Visual Studio 2017 Docker Tools](https://docs.microsoft.com/en-us/dotnet/core/docker/visual-studio-tools-for-docker). You can even hit breakpoints in your code as it runs in the container. Visual Studio Docker Tools also enables debugging multiple containers at once in a project. (This is useful if your ASP.NET WebApp and WebAPI are running in separate containers.) I recommend this a [short demo](https://channel9.msdn.com/events/Connect/2016/172?term=docker) or a longer [deep dive](https://channel9.msdn.com/Blogs/Seth-Juarez/Visual-Studio-Docker-Tools-for-building-ASPNET-Core-Web-Apps-The-September-Release) if this interests you.

You can also use Visual Studio for Mac docker tools if you are on MacOS. If you are working on Linux it can work in Visual Studio Code, but we do not have up-to-date documentation so it will involve some more configuring.

**Comment by jamestharpe** [comment]
I'm trying to get it to work with VS Code on Windows and it's unclear what "configuring" needs to be done to get it to work. Can you at least point me in the right direction?

**Comment by kendrahavens** [comment]
Sorry it took longer to get back to you. We were estimating the cost of covering this as a supported scenario on our end.

For now our resources are very focused on the Visual Studio scenario and we do not have a well supported workflow for using Visual Studio Code. There is an older vscode tool called [yo docker](https://github.com/Microsoft/generator-docker) that may help you learn how to configure this flow.

I'll close this issue since our team won't be directly supporting this scenario.
