### ISSUE TITLE
Create multi-arch example 

### ISSUE THREAD

**Issue by AceHack** [dotnet/dotnet-docker-samples#98]
Please create example of creating multi-arch image that targets windows, Linux, arm, etc...

https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

**Comment by richlander** [comment]
This one does that. No?

https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-prod

**Comment by AceHack** [comment]
@richlander No this does not build a multi-arch i.e. manifest list.  It can build a single arm docker image but it does not build multiple images for different platforms and then put them all behind a single multi-arch tag.

https://blog.docker.com/2017/11/multi-arch-all-the-things/
https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

More info on the subject.

**Comment by MichaelSimons** [comment]
I believe Creating multi-arch images is something that would be best covered by Docker documentation.  I say that because there is a lot to understand around this topic.  I believe this documentation will come once Docker has a tooling experience ([active PR](https://github.com/docker/cli/pull/138)) for this.  

I'm curious how many people are interested in this topic and would like to see a .NET Core sample for creating multi-arch images?

**Comment by AceHack** [comment]
@MichaelSimons well since I created the issue, I am for sure.  :)  I can tell you we are in the process of moving from Service Fabric on Windows to Kubernetes on Linux so it would be very helpful for us during this period to have our teams build multi-arch tags.  This will make the transition much easier.  Thanks.

**Comment by AceHack** [comment]
Also, this is what I'm in the processing of using right now
https://github.com/estesp/manifest-tool

But so far it's very unclear how I set up a CI/CD pipeline that can target both Windows and Linux.

Also on a side note, we do have ARM IoT devices that would be a great bonus to have images that could run on those as well.  I've been looking into https://hub.docker.com/u/multiarch/  Thanks.

**Comment by MichaelSimons** [comment]
We utilize the https://github.com/estesp/manifest-tool tooling internally to produce the manifest based tags for the microsoft/dotnet Docker repo.  Providing samples on producing manifests is something best for Docker itself to provide.  Once Docker has a tooling story around this, we may consider providing a sample since .NET Core is cross platform pending a demand for it.
